/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

package org.testng.test;

import org.testng.Assert;
import org.testng.annotations.Test;]\

//Assert.assertEquals(testscases)

class AppTest {

    @Test void task6() {
          List<Integer> num2 = new ArrayList<Integer>();
        int length = perfect.size();
        for (int i= 0; i<length; i++ ){
            num2.add(perfect.get(i));

        }
        Collections.sort(perfect);
        for (int i=0; i < length; i++){
            if (perfect.get(i) != num2.get(i)){
                return false;
            }
            else{
                return true;
            }
            
        }

        }

}
